#pragma once
#include <map>
#include <string>

class LuaKeyMap
{
public:
	inline static std::map<std::string, Keys> Keys = {
		{"Unknown", Keys::UNKNOWN},
		{"Space", Keys::SPACE},
		{"Apostrophe", Keys::APOSTROPHE},
		{"Comma", Keys::COMMA},
		{"Minus", Keys::MINUS},
		{"Period", Keys::PERIOD},
		{"Slash", Keys::SLASH},
		{"Zero", Keys::ZERO},
		{"One", Keys::ONE},
		{"Two", Keys::TWO},
		{"Three", Keys::THREE},
		{"Four", Keys::FOUR},
		{"Five", Keys::FIVE},
		{"Six", Keys::SIX},
		{"Seven", Keys::SEVEN},
		{"Eight", Keys::EIGHT},
		{"Nine", Keys::NINE},
		{"Semicolon", Keys::SEMICOLON},
		{"Equal", Keys::EQUAL},
		{"A", Keys::A},
		{"B", Keys::B},
		{"C", Keys::C},
		{"D", Keys::E},
		{"F", Keys::F},
		{"G", Keys::G},
		{"H", Keys::H},
		{"I", Keys::I},
		{"J", Keys::J},
		{"K", Keys::K},
		{"L", Keys::L},
		{"M", Keys::M},
		{"N", Keys::N},
		{"O", Keys::O},
		{"P", Keys::P},
		{"Q", Keys::Q},
		{"R", Keys::R},
		{"S", Keys::S},
		{"T", Keys::T},
		{"U", Keys::U},
		{"V", Keys::V},
		{"W", Keys::W},
		{"X", Keys::X},
		{"Y", Keys::Y},
		{"Z", Keys::Z},
		{"Left Bracket", Keys::LEFT_BRACKET},
		{"Backslash", Keys::BACKSLASH},
		{"Right Bracket", Keys::RIGHT_BRACKET},
		{"Grave Accent", Keys::GRAVE_ACCENT},
		{"World 1", Keys::WORLD_1},
		{"World 2", Keys::WORLD_2},
		{"Escape", Keys::ESCAPE},
		{"Enter", Keys::ENTER},
		{"Tab", Keys::TAB},
		{"Backspace", Keys::BACKSPACE},
		{"Insert", Keys::INSERT},
		{"Delete", Keys::DELETE},
		{"Right", Keys::RIGHT},
		{"Left", Keys::LEFT},
		{"Down", Keys::DOWN},
		{"Up", Keys::UP},
		{"Page Up", Keys::PAGE_UP},
		{"Page Down", Keys::PAGE_DOWN},
		{"Home", Keys::HOME},
		{"End", Keys::END},
		{"Caps Lock", Keys::CAPS_LOCK},
		{"Scroll Lock", Keys::SCROLL_LOCK},
		{"Num Lock", Keys::NUM_LOCK},
		{"Print Screen", Keys::PRINT_SCREEN},
		{"Pause", Keys::PAUSE},
		{"F1", Keys::F1},
		{"F2", Keys::F2},
		{"F3", Keys::F3},
		{"F4", Keys::F4},
		{"F5", Keys::F5},
		{"F6", Keys::F6},
		{"F7", Keys::F7},
		{"F8", Keys::F8},
		{"F9", Keys::F9},
		{"F10", Keys::F10},
		{"F11", Keys::F11},
		{"F12", Keys::F12},
		{"F13", Keys::F13},
		{"F14", Keys::F14},
		{"F15", Keys::F15},
		{"F16", Keys::F16},
		{"F17", Keys::F17},
		{"F18", Keys::F18},
		{"F19", Keys::F19},
		{"F20", Keys::F20},
		{"F21", Keys::F21},
		{"F22", Keys::F22},
		{"F23", Keys::F23},
		{"F24", Keys::F24},
		{"F25", Keys::F25},
		{"KP 0", Keys::KP_0},
		{"KP 1", Keys::KP_1},
		{"KP 2", Keys::KP_2},
		{"KP 3", Keys::KP_3},
		{"KP 4", Keys::KP_4},
		{"KP 5", Keys::KP_5},
		{"KP 6", Keys::KP_6},
		{"KP 7", Keys::KP_7},
		{"KP 8", Keys::KP_8},
		{"KP 9", Keys::KP_9},
		{"KP Decimal", Keys::KP_DECIMAL},
		{"KP Divide", Keys::KP_DIVIDE},
		{"KP Multiply", Keys::KP_MULTIPLY},
		{"KP Subtract", Keys::KP_SUBTRACT},
		{"KP Add", Keys::KP_ADD},
		{"KP Enter", Keys::KP_ENTER},
		{"KP Equal", Keys::KP_EQUAL},
		{"Left Shift", Keys::LEFT_SHIFT},
		{"Left Control", Keys::LEFT_CONTROL},
		{"Left Alt", Keys::LEFT_ALT},
		{"Right Shift", Keys::RIGHT_SHIFT},
		{"Right Control", Keys::RIGHT_CONTROL},
		{"Right Alt", Keys::RIGHT_ALT},
		{"Right Super", Keys::RIGHT_SUPER},
		{"Menu", Keys::MENU}
	};
};
