#pragma once

#include "../Interactive.h"
#include "../includes/RendererIncludes.h"
#include "../includes/InputIncludes.h"
#include "../includes/EcIncludes.h"
#include "../includes/TextureIncludes.h"
#include "../includes/Components.h"
#include "../InteractiveObject.h"
#include "../GarbageCollector.h"
#include "../script-system/ComponentFactory.h"
#include "../asset-system/AssetManager.h"
#include "../asset-system/AssetDatabase.h"
#include "../external/imgui/imgui.h"
#include "../external/imgui/imgui_impl_glfw.h"
#include "../external/imgui/imgui_impl_opengl3.h"